import ipaddr from 'ipaddr.js';

export type ParsedRecord = { name: string; type: string; value: string };
export type ParseResult = { records: ParsedRecord[]; skipped: number };

// Detect IP version for plain-IP rewrites and hosts format
function ipType(ip: string): 'A' | 'AAAA' | null {
	if (!ipaddr.isValid(ip)) return null;
	return ipaddr.parse(ip).kind() === 'ipv4' ? 'A' : 'AAAA';
}

export function parseFilterRules(text: string): ParseResult {
	const records: ParsedRecord[] = [];
	let skipped = 0;

	for (const raw of text.split('\n')) {
		const line = raw.trim();

		// Blank / comment / whitelist
		if (!line || line.startsWith('!') || line.startsWith('#') || line.startsWith('@@')) continue;

		// Auto-blocking exclusion lines generated by this app (contain ~)
		if (line.includes('~')) continue;

		let parsed: ParsedRecord | null = null;

		// ── Format 1: hostname$dnsrewrite=NOERROR;TYPE;VALUE ──────────────────
		// e.g. example.com$dnsrewrite=NOERROR;A;1.2.3.4
		let m = line.match(/^([^|][^$]*)?\$dnsrewrite=NOERROR;([^;]+);(.*)$/);
		if (m) {
			parsed = { name: m[1].trim(), type: m[2].trim(), value: m[3].trim() };
		}

		// ── Format 2: ||hostname^$dnstype=TYPE,dnsrewrite=NOERROR;; (NODATA) ──
		if (!parsed) {
			m = line.match(/^\|\|([^|^]+)\^\$dnstype=([^,]+),dnsrewrite=NOERROR;;$/);
			if (m) {
				parsed = { name: m[1].trim(), type: m[2].trim(), value: '' };
			}
		}

		// ── Format 3: ||hostname^$dnstype=TYPE,dnsrewrite=REFUSED ─────────────
		if (!parsed) {
			m = line.match(/^\|\|([^|^]+)\^\$dnstype=([^,]+),dnsrewrite=REFUSED$/);
			if (m) {
				parsed = { name: m[1].trim(), type: 'REFUSED', value: m[2].trim() };
			}
		}

		// ── Format 4: ||hostname^$dnstype=TYPE,dnsrewrite=NXDOMAIN;; ──────────
		if (!parsed) {
			m = line.match(/^\|\|([^|^]+)\^\$dnstype=([^,]+),dnsrewrite=NXDOMAIN;;$/);
			if (m) {
				parsed = { name: m[1].trim(), type: 'NXDOMAIN', value: m[2].trim() };
			}
		}

		// ── Format 5: hostname$dnsrewrite=REFUSED ────────────────────────────
		if (!parsed) {
			m = line.match(/^([^|][^$]*)?\$dnsrewrite=REFUSED$/);
			if (m) {
				parsed = { name: m[1].trim(), type: 'REFUSED', value: '' };
			}
		}

		// ── Format 6: hostname$dnsrewrite=NXDOMAIN;; ─────────────────────────
		if (!parsed) {
			m = line.match(/^([^|][^$]*)?\$dnsrewrite=NXDOMAIN;;$/);
			if (m) {
				parsed = { name: m[1].trim(), type: 'NXDOMAIN', value: '' };
			}
		}

		// ── Format 7: ||hostname^ (simple block rule) ─────────────────────────
		if (!parsed) {
			m = line.match(/^\|\|([^|^]+)\^$/);
			if (m) {
				parsed = { name: m[1].trim(), type: 'NXDOMAIN', value: '' };
			}
		}

		// ── Format 8: IP hostname (hosts file format) ─────────────────────────
		if (!parsed) {
			m = line.match(/^(\S+)\s+(\S+)$/);
			if (m) {
				const t = ipType(m[1]);
				if (t) {
					parsed = { name: m[2].trim(), type: t, value: m[1].trim() };
				}
			}
		}

		// ── Format 9: hostname$dnsrewrite=IP (shorthand) ─────────────────────
		if (!parsed) {
			m = line.match(/^([^|][^$]*)?\$dnsrewrite=(\S+)$/);
			if (m) {
				const t = ipType(m[2]);
				if (t) {
					parsed = { name: m[1].trim(), type: t, value: m[2].trim() };
				}
			}
		}

		if (parsed) {
			records.push(parsed);
		} else {
			skipped++;
		}
	}

	return { records, skipped };
}
